name: pydropsonde_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - bottleneck
  - ca-certificates
  - certifi
  - ipykernel
  - ipython
  - myst-parser
  - nbsphinx
  - netcdf4
  - numpy
  - openssl
  - pre-commit
  - pytest
  - sphinx
  - sphinx-autobuild
  - xarray
  - zarr
  - pip
  - pip:
    - moist-thermodynamics
    - tqdm
    - sphinx-autodoc2
    - sphinx-book-theme
    - sphinx-last-updated-by-git
    - -e .
