name: pydropsonde_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - aiohttp
  - bottleneck
  - ca-certificates
  - certifi
  - ipykernel
  - ipython
  - myst-parser
  - nbsphinx
  - netcdf4
  - numpy
  - openssl
  - pillow
  - pre-commit
  - pytest
  - qrcode
  - requests
  - sphinx
  - sphinx-autobuild
  - xarray
  - xhistogram
  - zarr >2,<3
  - pip
  - pip:
    - fsspec!=0.9.0
    - moist-thermodynamics
    - tqdm
    - sphinx-autodoc2
    - sphinx-book-theme
    - sphinx-last-updated-by-git
    - -e .
