[build-system]
requires=["setuptools>=43.0.0","wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "halodrops"
version = "2023.04"
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "Geet George", email = "geet.george@mpimet.mpg.de"}]

