# This workflow will install Python dependencies using mamba, run tests and check pre-commit

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10
    - uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: 'latest'
        init-shell: bash
        generate-run-shell: true
        environment-name: testenv
        environment-file: environment.yml
    - name: Run pytest in micromamba environment
      run: |
        micromamba install -n testenv pytest
        micromamba run -n testenv pytest --import-mode=importlib .
    - name: pre-commit
      uses: pre-commit/action@v3.0.0
